In [3]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('images.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [12]:
print(x_test)
print(y_train)
print(y_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 0 0
 0 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 1 1 0 0
 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0
 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0 1 0]
[0 1 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0 1
 1 1 0 0 1 1 1 0 1]


In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [8]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]]


In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[25  0]
 [ 1 20]]


0.9782608695652174

In [10]:
classifier.predict_proba(x_test)

array([[9.21195584e-01, 7.88044163e-02],
       [6.51151171e-03, 9.93488488e-01],
       [5.93607384e-02, 9.40639262e-01],
       [9.62188416e-01, 3.78115839e-02],
       [1.34971297e-01, 8.65028703e-01],
       [9.77043368e-01, 2.29566322e-02],
       [6.77649778e-04, 9.99322350e-01],
       [7.83133365e-01, 2.16866635e-01],
       [8.11848089e-02, 9.18815191e-01],
       [9.00496209e-01, 9.95037912e-02],
       [5.71189476e-01, 4.28810524e-01],
       [8.51422797e-01, 1.48577203e-01],
       [8.97436523e-01, 1.02563477e-01],
       [9.77802920e-01, 2.21970804e-02],
       [7.91854427e-01, 2.08145573e-01],
       [9.02821761e-01, 9.71782388e-02],
       [9.52147669e-01, 4.78523315e-02],
       [9.37691164e-01, 6.23088356e-02],
       [9.43991994e-01, 5.60080062e-02],
       [8.96149426e-01, 1.03850574e-01],
       [8.45959440e-01, 1.54040560e-01],
       [1.63448193e-01, 8.36551807e-01],
       [1.01621327e-02, 9.89837867e-01],
       [8.87309745e-01, 1.12690255e-01],
       [1.973010

In [11]:
import joblib
joblib.dump(classifier, 'model.joblib')

['model.joblib']